name: Test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.6
        ports:
        - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: test_password

    steps:
    - name: Show variables
      run: |
        mysql -h 127.0.0.1 --port 3306 -u root -ptest_password -e "SHOW GLOBAL VARIABLES LIKE 'innodb_ft_min_token_size';"
    - uses: actions/checkout@v2
    - name: Add conf
      run: |
        docker cp ./mysql/conf.d/test.cnf {{ job.services.mysql.id }}:/etc/mysql/conf.d/
    - name: Restart mysql
      run: |
        docker restart {{ job.services.mysql.id }}
    - name: Show variables
      run: |
        mysql -h 127.0.0.1 --port 3306 -u root -ptest_password -e "SHOW GLOBAL VARIABLES LIKE 'innodb_ft_min_token_size';"
