name: Test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.6
        ports:
        - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: test_password

    steps:
    - name: Show variables
      run: |
        set -eux
        mysql -h 127.0.0.1 --port 3306 -u root -ptest_password -e "SHOW GLOBAL VARIABLES LIKE 'innodb_ft_min_token_size';"
    - uses: actions/checkout@v2
    - name: Add conf
      run: |
        set -eux
        docker cp ./mysql/conf.d/test.cnf ${{ job.services.mysql.id }}:/etc/mysql/conf.d/
    - name: Restart mysql
      run: |
        set -eux
        docker restart ${{ job.services.mysql.id }}
        for sleep in 0 ${WAITS:- 1 2 4 8 15 25 100}; do
          sleep "$sleep"
          health_status=`docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" ${{ job.services.mysql.id }}`
          if [ 'starting' != "$health_status" ]; then
            exit 0
          fi
        done
        exit 1
    - name: Show variables
      run: |
        set -eux
        mysql -h 127.0.0.1 --port 3306 -u root -ptest_password -e "SHOW GLOBAL VARIABLES LIKE 'innodb_ft_min_token_size';"
